//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Ifuunciones")]
    public interface Ifuunciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifuunciones/Create", ReplyAction="http://tempuri.org/Ifuunciones/CreateResponse")]
        void Create(string id, string nombre, string apellidos, string direccion, string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifuunciones/Read", ReplyAction="http://tempuri.org/Ifuunciones/ReadResponse")]
        string[] Read(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifuunciones/delete", ReplyAction="http://tempuri.org/Ifuunciones/deleteResponse")]
        bool delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifuunciones/update", ReplyAction="http://tempuri.org/Ifuunciones/updateResponse")]
        bool update(string id, string nombre, string apellidos, string direccion, string numero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IfuuncionesChannel : crud1.ServiceReference1.Ifuunciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IfuuncionesClient : System.ServiceModel.ClientBase<crud1.ServiceReference1.Ifuunciones>, crud1.ServiceReference1.Ifuunciones {
        
        public IfuuncionesClient() {
        }
        
        public IfuuncionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IfuuncionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IfuuncionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IfuuncionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(string id, string nombre, string apellidos, string direccion, string numero) {
            base.Channel.Create(id, nombre, apellidos, direccion, numero);
        }
        
        public string[] Read(string id) {
            return base.Channel.Read(id);
        }
        
        public bool delete(string id) {
            return base.Channel.delete(id);
        }
        
        public bool update(string id, string nombre, string apellidos, string direccion, string numero) {
            return base.Channel.update(id, nombre, apellidos, direccion, numero);
        }
    }
}
